# Project Name
TARGET = OLED_SSD130x4WireSPI

# Sources
CPP_SOURCES = OLED_SSD130x4WireSPI.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
