var annotated_dup =
[
    [ "daisy", "namespacedaisy.html", [
      [ "MAX11300Types", "namespacedaisy_1_1_m_a_x11300_types.html", [
        [ "DmaBuffer", "structdaisy_1_1_m_a_x11300_types_1_1_dma_buffer.html", "structdaisy_1_1_m_a_x11300_types_1_1_dma_buffer" ]
      ] ],
      [ "patch_sm", "namespacedaisy_1_1patch__sm.html", [
        [ "DaisyPatchSM", "classdaisy_1_1patch__sm_1_1_daisy_patch_s_m.html", "classdaisy_1_1patch__sm_1_1_daisy_patch_s_m" ]
      ] ],
      [ "AbstractMenu", "classdaisy_1_1_abstract_menu.html", "classdaisy_1_1_abstract_menu" ],
      [ "AdcChannelConfig", "structdaisy_1_1_adc_channel_config.html", "structdaisy_1_1_adc_channel_config" ],
      [ "AdcHandle", "classdaisy_1_1_adc_handle.html", "classdaisy_1_1_adc_handle" ],
      [ "Ak4556", "classdaisy_1_1_ak4556.html", "classdaisy_1_1_ak4556" ],
      [ "AllNotesOffEvent", "structdaisy_1_1_all_notes_off_event.html", "structdaisy_1_1_all_notes_off_event" ],
      [ "AllSoundOffEvent", "structdaisy_1_1_all_sound_off_event.html", "structdaisy_1_1_all_sound_off_event" ],
      [ "AnalogControl", "classdaisy_1_1_analog_control.html", "classdaisy_1_1_analog_control" ],
      [ "Apds9960", "classdaisy_1_1_apds9960.html", "classdaisy_1_1_apds9960" ],
      [ "Apds9960I2CTransport", "classdaisy_1_1_apds9960_i2_c_transport.html", "classdaisy_1_1_apds9960_i2_c_transport" ],
      [ "AudioHandle", "classdaisy_1_1_audio_handle.html", "classdaisy_1_1_audio_handle" ],
      [ "ButtonMonitor", "classdaisy_1_1_button_monitor.html", "classdaisy_1_1_button_monitor" ],
      [ "ChannelModeEvent", "structdaisy_1_1_channel_mode_event.html", "structdaisy_1_1_channel_mode_event" ],
      [ "ChannelPressureEvent", "structdaisy_1_1_channel_pressure_event.html", "structdaisy_1_1_channel_pressure_event" ],
      [ "Color", "classdaisy_1_1_color.html", "classdaisy_1_1_color" ],
      [ "ControlChangeEvent", "structdaisy_1_1_control_change_event.html", "structdaisy_1_1_control_change_event" ],
      [ "CpuLoadMeter", "classdaisy_1_1_cpu_load_meter.html", "classdaisy_1_1_cpu_load_meter" ],
      [ "DacHandle", "classdaisy_1_1_dac_handle.html", "classdaisy_1_1_dac_handle" ],
      [ "DaisyField", "classdaisy_1_1_daisy_field.html", "classdaisy_1_1_daisy_field" ],
      [ "DaisyLegio", "classdaisy_1_1_daisy_legio.html", "classdaisy_1_1_daisy_legio" ],
      [ "DaisyPatch", "classdaisy_1_1_daisy_patch.html", "classdaisy_1_1_daisy_patch" ],
      [ "DaisyPetal", "classdaisy_1_1_daisy_petal.html", "classdaisy_1_1_daisy_petal" ],
      [ "DaisyPod", "classdaisy_1_1_daisy_pod.html", "classdaisy_1_1_daisy_pod" ],
      [ "DaisySeed", "classdaisy_1_1_daisy_seed.html", "classdaisy_1_1_daisy_seed" ],
      [ "DaisyVersio", "classdaisy_1_1_daisy_versio.html", "classdaisy_1_1_daisy_versio" ],
      [ "DotStar", "classdaisy_1_1_dot_star.html", "classdaisy_1_1_dot_star" ],
      [ "DotStarSpiTransport", "classdaisy_1_1_dot_star_spi_transport.html", "classdaisy_1_1_dot_star_spi_transport" ],
      [ "Dps310", "classdaisy_1_1_dps310.html", "classdaisy_1_1_dps310" ],
      [ "Dps310I2CTransport", "classdaisy_1_1_dps310_i2_c_transport.html", "classdaisy_1_1_dps310_i2_c_transport" ],
      [ "Dps310SpiTransport", "classdaisy_1_1_dps310_spi_transport.html", "classdaisy_1_1_dps310_spi_transport" ],
      [ "Encoder", "classdaisy_1_1_encoder.html", "classdaisy_1_1_encoder" ],
      [ "FatFSInterface", "classdaisy_1_1_fat_f_s_interface.html", "classdaisy_1_1_fat_f_s_interface" ],
      [ "FIFO", "classdaisy_1_1_f_i_f_o.html", "classdaisy_1_1_f_i_f_o" ],
      [ "FIFOBase", "classdaisy_1_1_f_i_f_o_base.html", "classdaisy_1_1_f_i_f_o_base" ],
      [ "FixedCapStr", "classdaisy_1_1_fixed_cap_str.html", "classdaisy_1_1_fixed_cap_str" ],
      [ "FixedCapStrBase", "classdaisy_1_1_fixed_cap_str_base.html", "classdaisy_1_1_fixed_cap_str_base" ],
      [ "FullScreenItemMenu", "classdaisy_1_1_full_screen_item_menu.html", "classdaisy_1_1_full_screen_item_menu" ],
      [ "GateIn", "classdaisy_1_1_gate_in.html", "classdaisy_1_1_gate_in" ],
      [ "GPIO", "classdaisy_1_1_g_p_i_o.html", "classdaisy_1_1_g_p_i_o" ],
      [ "I2CHandle", "classdaisy_1_1_i2_c_handle.html", "classdaisy_1_1_i2_c_handle" ],
      [ "Icm20948", "classdaisy_1_1_icm20948.html", "classdaisy_1_1_icm20948" ],
      [ "Icm20948I2CTransport", "classdaisy_1_1_icm20948_i2_c_transport.html", "classdaisy_1_1_icm20948_i2_c_transport" ],
      [ "Icm20948SpiTransport", "classdaisy_1_1_icm20948_spi_transport.html", "classdaisy_1_1_icm20948_spi_transport" ],
      [ "LcdHD44780", "classdaisy_1_1_lcd_h_d44780.html", "classdaisy_1_1_lcd_h_d44780" ],
      [ "Led", "classdaisy_1_1_led.html", "classdaisy_1_1_led" ],
      [ "LedDriverPca9685", "classdaisy_1_1_led_driver_pca9685.html", "classdaisy_1_1_led_driver_pca9685" ],
      [ "LocalControlEvent", "structdaisy_1_1_local_control_event.html", "structdaisy_1_1_local_control_event" ],
      [ "Logger", "classdaisy_1_1_logger.html", "classdaisy_1_1_logger" ],
      [ "Logger< LOGGER_NONE >", "classdaisy_1_1_logger_3_01_l_o_g_g_e_r___n_o_n_e_01_4.html", "classdaisy_1_1_logger_3_01_l_o_g_g_e_r___n_o_n_e_01_4" ],
      [ "LoggerImpl", "classdaisy_1_1_logger_impl.html", null ],
      [ "LoggerImpl< LOGGER_EXTERNAL >", "classdaisy_1_1_logger_impl_3_01_l_o_g_g_e_r___e_x_t_e_r_n_a_l_01_4.html", null ],
      [ "LoggerImpl< LOGGER_INTERNAL >", "classdaisy_1_1_logger_impl_3_01_l_o_g_g_e_r___i_n_t_e_r_n_a_l_01_4.html", null ],
      [ "LoggerImpl< LOGGER_SEMIHOST >", "classdaisy_1_1_logger_impl_3_01_l_o_g_g_e_r___s_e_m_i_h_o_s_t_01_4.html", null ],
      [ "MappedFloatValue", "classdaisy_1_1_mapped_float_value.html", "classdaisy_1_1_mapped_float_value" ],
      [ "MappedIntValue", "classdaisy_1_1_mapped_int_value.html", "classdaisy_1_1_mapped_int_value" ],
      [ "MappedStringListValue", "classdaisy_1_1_mapped_string_list_value.html", "classdaisy_1_1_mapped_string_list_value" ],
      [ "MappedValue", "classdaisy_1_1_mapped_value.html", "classdaisy_1_1_mapped_value" ],
      [ "MAX11300Driver", "classdaisy_1_1_m_a_x11300_driver.html", "classdaisy_1_1_m_a_x11300_driver" ],
      [ "MAX11300MultiSlaveSpiTransport", "classdaisy_1_1_m_a_x11300_multi_slave_spi_transport.html", "classdaisy_1_1_m_a_x11300_multi_slave_spi_transport" ],
      [ "Mcp23017Transport", "classdaisy_1_1_mcp23017_transport.html", "classdaisy_1_1_mcp23017_transport" ],
      [ "Mcp23X17", "classdaisy_1_1_mcp23_x17.html", "classdaisy_1_1_mcp23_x17" ],
      [ "MidiEvent", "structdaisy_1_1_midi_event.html", "structdaisy_1_1_midi_event" ],
      [ "MidiHandler", "classdaisy_1_1_midi_handler.html", "classdaisy_1_1_midi_handler" ],
      [ "MidiParser", "classdaisy_1_1_midi_parser.html", "classdaisy_1_1_midi_parser" ],
      [ "MidiUartTransport", "classdaisy_1_1_midi_uart_transport.html", "classdaisy_1_1_midi_uart_transport" ],
      [ "MidiUsbTransport", "classdaisy_1_1_midi_usb_transport.html", "classdaisy_1_1_midi_usb_transport" ],
      [ "MonoModeOnEvent", "structdaisy_1_1_mono_mode_on_event.html", "structdaisy_1_1_mono_mode_on_event" ],
      [ "Mpr121", "classdaisy_1_1_mpr121.html", "classdaisy_1_1_mpr121" ],
      [ "Mpr121I2CTransport", "classdaisy_1_1_mpr121_i2_c_transport.html", "classdaisy_1_1_mpr121_i2_c_transport" ],
      [ "MTCQuarterFrameEvent", "structdaisy_1_1_m_t_c_quarter_frame_event.html", "structdaisy_1_1_m_t_c_quarter_frame_event" ],
      [ "MultiSlaveSpiHandle", "classdaisy_1_1_multi_slave_spi_handle.html", "classdaisy_1_1_multi_slave_spi_handle" ],
      [ "NeoPixel", "classdaisy_1_1_neo_pixel.html", "classdaisy_1_1_neo_pixel" ],
      [ "NeoPixelI2CTransport", "classdaisy_1_1_neo_pixel_i2_c_transport.html", "classdaisy_1_1_neo_pixel_i2_c_transport" ],
      [ "NeoTrellis", "classdaisy_1_1_neo_trellis.html", "classdaisy_1_1_neo_trellis" ],
      [ "NeoTrellisI2CTransport", "classdaisy_1_1_neo_trellis_i2_c_transport.html", "classdaisy_1_1_neo_trellis_i2_c_transport" ],
      [ "NoteOffEvent", "structdaisy_1_1_note_off_event.html", "structdaisy_1_1_note_off_event" ],
      [ "NoteOnEvent", "structdaisy_1_1_note_on_event.html", "structdaisy_1_1_note_on_event" ],
      [ "OledDisplay", "classdaisy_1_1_oled_display.html", "classdaisy_1_1_oled_display" ],
      [ "OmniModeOffEvent", "structdaisy_1_1_omni_mode_off_event.html", "structdaisy_1_1_omni_mode_off_event" ],
      [ "OmniModeOnEvent", "structdaisy_1_1_omni_mode_on_event.html", "structdaisy_1_1_omni_mode_on_event" ],
      [ "OneBitGraphicsDisplay", "classdaisy_1_1_one_bit_graphics_display.html", "classdaisy_1_1_one_bit_graphics_display" ],
      [ "OneBitGraphicsDisplayImpl", "classdaisy_1_1_one_bit_graphics_display_impl.html", "classdaisy_1_1_one_bit_graphics_display_impl" ],
      [ "Parameter", "classdaisy_1_1_parameter.html", "classdaisy_1_1_parameter" ],
      [ "Pcm3060", "classdaisy_1_1_pcm3060.html", "classdaisy_1_1_pcm3060" ],
      [ "PersistentStorage", "classdaisy_1_1_persistent_storage.html", "classdaisy_1_1_persistent_storage" ],
      [ "Pin", "structdaisy_1_1_pin.html", "structdaisy_1_1_pin" ],
      [ "PitchBendEvent", "structdaisy_1_1_pitch_bend_event.html", "structdaisy_1_1_pitch_bend_event" ],
      [ "PolyModeOnEvent", "structdaisy_1_1_poly_mode_on_event.html", "structdaisy_1_1_poly_mode_on_event" ],
      [ "PolyphonicKeyPressureEvent", "structdaisy_1_1_polyphonic_key_pressure_event.html", "structdaisy_1_1_polyphonic_key_pressure_event" ],
      [ "PotMonitor", "classdaisy_1_1_pot_monitor.html", "classdaisy_1_1_pot_monitor" ],
      [ "ProgramChangeEvent", "structdaisy_1_1_program_change_event.html", "structdaisy_1_1_program_change_event" ],
      [ "QSPIHandle", "classdaisy_1_1_q_s_p_i_handle.html", "classdaisy_1_1_q_s_p_i_handle" ],
      [ "Random", "classdaisy_1_1_random.html", "classdaisy_1_1_random" ],
      [ "Rectangle", "classdaisy_1_1_rectangle.html", "classdaisy_1_1_rectangle" ],
      [ "ResetAllControllersEvent", "structdaisy_1_1_reset_all_controllers_event.html", "structdaisy_1_1_reset_all_controllers_event" ],
      [ "RgbLed", "classdaisy_1_1_rgb_led.html", "classdaisy_1_1_rgb_led" ],
      [ "RingBuffer", "classdaisy_1_1_ring_buffer.html", "classdaisy_1_1_ring_buffer" ],
      [ "RingBuffer< T, 0 >", "classdaisy_1_1_ring_buffer_3_01_t_00_010_01_4.html", "classdaisy_1_1_ring_buffer_3_01_t_00_010_01_4" ],
      [ "SaiHandle", "classdaisy_1_1_sai_handle.html", "classdaisy_1_1_sai_handle" ],
      [ "ScopedIrqBlocker", "classdaisy_1_1_scoped_irq_blocker.html", "classdaisy_1_1_scoped_irq_blocker" ],
      [ "SdmmcHandler", "classdaisy_1_1_sdmmc_handler.html", "classdaisy_1_1_sdmmc_handler" ],
      [ "ShiftRegister4021", "classdaisy_1_1_shift_register4021.html", "classdaisy_1_1_shift_register4021" ],
      [ "SongPositionPointerEvent", "structdaisy_1_1_song_position_pointer_event.html", "structdaisy_1_1_song_position_pointer_event" ],
      [ "SongSelectEvent", "structdaisy_1_1_song_select_event.html", "structdaisy_1_1_song_select_event" ],
      [ "SpiHandle", "classdaisy_1_1_spi_handle.html", "classdaisy_1_1_spi_handle" ],
      [ "SSD130x4WireSoftSpiTransport", "classdaisy_1_1_s_s_d130x4_wire_soft_spi_transport.html", "classdaisy_1_1_s_s_d130x4_wire_soft_spi_transport" ],
      [ "SSD130x4WireSpiTransport", "classdaisy_1_1_s_s_d130x4_wire_spi_transport.html", "classdaisy_1_1_s_s_d130x4_wire_spi_transport" ],
      [ "SSD130xDriver", "classdaisy_1_1_s_s_d130x_driver.html", "classdaisy_1_1_s_s_d130x_driver" ],
      [ "SSD130xI2CTransport", "classdaisy_1_1_s_s_d130x_i2_c_transport.html", "classdaisy_1_1_s_s_d130x_i2_c_transport" ],
      [ "Stack", "classdaisy_1_1_stack.html", "classdaisy_1_1_stack" ],
      [ "StackBase", "classdaisy_1_1_stack_base.html", "classdaisy_1_1_stack_base" ],
      [ "Switch", "classdaisy_1_1_switch.html", "classdaisy_1_1_switch" ],
      [ "Switch3", "classdaisy_1_1_switch3.html", "classdaisy_1_1_switch3" ],
      [ "System", "classdaisy_1_1_system.html", "classdaisy_1_1_system" ],
      [ "SystemExclusiveEvent", "structdaisy_1_1_system_exclusive_event.html", "structdaisy_1_1_system_exclusive_event" ],
      [ "TimerHandle", "classdaisy_1_1_timer_handle.html", "classdaisy_1_1_timer_handle" ],
      [ "Tlv493d", "classdaisy_1_1_tlv493d.html", "classdaisy_1_1_tlv493d" ],
      [ "Tlv493dI2CTransport", "classdaisy_1_1_tlv493d_i2_c_transport.html", "classdaisy_1_1_tlv493d_i2_c_transport" ],
      [ "UartHandler", "classdaisy_1_1_uart_handler.html", "classdaisy_1_1_uart_handler" ],
      [ "UI", "classdaisy_1_1_u_i.html", "classdaisy_1_1_u_i" ],
      [ "UiCanvasDescriptor", "structdaisy_1_1_ui_canvas_descriptor.html", "structdaisy_1_1_ui_canvas_descriptor" ],
      [ "UiEventQueue", "classdaisy_1_1_ui_event_queue.html", "classdaisy_1_1_ui_event_queue" ],
      [ "UiPage", "classdaisy_1_1_ui_page.html", "classdaisy_1_1_ui_page" ],
      [ "USBHostHandle", "classdaisy_1_1_u_s_b_host_handle.html", "classdaisy_1_1_u_s_b_host_handle" ],
      [ "VoctCalibration", "classdaisy_1_1_voct_calibration.html", "classdaisy_1_1_voct_calibration" ],
      [ "WAV_FormatTypeDef", "structdaisy_1_1_w_a_v___format_type_def.html", "structdaisy_1_1_w_a_v___format_type_def" ],
      [ "WaveTableLoader", "classdaisy_1_1_wave_table_loader.html", "classdaisy_1_1_wave_table_loader" ],
      [ "WavFileInfo", "structdaisy_1_1_wav_file_info.html", "structdaisy_1_1_wav_file_info" ],
      [ "WavPlayer", "classdaisy_1_1_wav_player.html", "classdaisy_1_1_wav_player" ],
      [ "WavWriter", "classdaisy_1_1_wav_writer.html", "classdaisy_1_1_wav_writer" ],
      [ "Wm8731", "classdaisy_1_1_wm8731.html", "classdaisy_1_1_wm8731" ]
    ] ],
    [ "dsy_gpio", "structdsy__gpio.html", "structdsy__gpio" ],
    [ "dsy_gpio_pin", "structdsy__gpio__pin.html", "structdsy__gpio__pin" ],
    [ "DSY_SD_CardInfoTypeDef", "struct_d_s_y___s_d___card_info_type_def.html", "struct_d_s_y___s_d___card_info_type_def" ],
    [ "FontDef", "struct_font_def.html", "struct_font_def" ],
    [ "SdramHandle", "class_sdram_handle.html", "class_sdram_handle" ],
    [ "ShiftRegister595", "class_shift_register595.html", "class_shift_register595" ],
    [ "UsbHandle", "class_usb_handle.html", "class_usb_handle" ]
];