var hierarchy =
[
    [ "daisy::Tlv493d< Transport >::AccessMode_t", "structdaisy_1_1_tlv493d_1_1_access_mode__t.html", null ],
    [ "daisy::AdcChannelConfig", "structdaisy_1_1_adc_channel_config.html", null ],
    [ "daisy::AdcHandle", "classdaisy_1_1_adc_handle.html", null ],
    [ "daisy::Ak4556", "classdaisy_1_1_ak4556.html", null ],
    [ "daisy::AllNotesOffEvent", "structdaisy_1_1_all_notes_off_event.html", null ],
    [ "daisy::AllSoundOffEvent", "structdaisy_1_1_all_sound_off_event.html", null ],
    [ "daisy::AnalogControl", "classdaisy_1_1_analog_control.html", null ],
    [ "daisy::Apds9960< Transport >", "classdaisy_1_1_apds9960.html", null ],
    [ "daisy::Apds9960I2CTransport", "classdaisy_1_1_apds9960_i2_c_transport.html", null ],
    [ "daisy::AudioHandle", "classdaisy_1_1_audio_handle.html", null ],
    [ "daisy::NeoTrellis< Transport >::keyEvent::Bit", "structdaisy_1_1_neo_trellis_1_1key_event_1_1_bit.html", null ],
    [ "daisy::ButtonMonitor< BackendType, numButtons >", "classdaisy_1_1_button_monitor.html", null ],
    [ "daisy::ChannelModeEvent", "structdaisy_1_1_channel_mode_event.html", null ],
    [ "daisy::ChannelPressureEvent", "structdaisy_1_1_channel_pressure_event.html", null ],
    [ "daisy::Color", "classdaisy_1_1_color.html", null ],
    [ "daisy::Apds9960< Transport >::Config", "structdaisy_1_1_apds9960_1_1_config.html", null ],
    [ "daisy::Apds9960I2CTransport::Config", "structdaisy_1_1_apds9960_i2_c_transport_1_1_config.html", null ],
    [ "daisy::AudioHandle::Config", "structdaisy_1_1_audio_handle_1_1_config.html", null ],
    [ "daisy::DacHandle::Config", "structdaisy_1_1_dac_handle_1_1_config.html", null ],
    [ "daisy::DotStar< Transport >::Config", "structdaisy_1_1_dot_star_1_1_config.html", null ],
    [ "daisy::DotStarSpiTransport::Config", "structdaisy_1_1_dot_star_spi_transport_1_1_config.html", null ],
    [ "daisy::Dps310< Transport >::Config", "structdaisy_1_1_dps310_1_1_config.html", null ],
    [ "daisy::Dps310I2CTransport::Config", "structdaisy_1_1_dps310_i2_c_transport_1_1_config.html", null ],
    [ "daisy::Dps310SpiTransport::Config", "structdaisy_1_1_dps310_spi_transport_1_1_config.html", null ],
    [ "daisy::FatFSInterface::Config", "structdaisy_1_1_fat_f_s_interface_1_1_config.html", null ],
    [ "daisy::GPIO::Config", "structdaisy_1_1_g_p_i_o_1_1_config.html", null ],
    [ "daisy::I2CHandle::Config", "structdaisy_1_1_i2_c_handle_1_1_config.html", null ],
    [ "daisy::Icm20948< Transport >::Config", "structdaisy_1_1_icm20948_1_1_config.html", null ],
    [ "daisy::Icm20948I2CTransport::Config", "structdaisy_1_1_icm20948_i2_c_transport_1_1_config.html", null ],
    [ "daisy::Icm20948SpiTransport::Config", "structdaisy_1_1_icm20948_spi_transport_1_1_config.html", null ],
    [ "daisy::LcdHD44780::Config", "structdaisy_1_1_lcd_h_d44780_1_1_config.html", null ],
    [ "daisy::MAX11300Driver< Transport, num_devices >::Config", "structdaisy_1_1_m_a_x11300_driver_1_1_config.html", null ],
    [ "daisy::MAX11300MultiSlaveSpiTransport::Config< numDevices >", "structdaisy_1_1_m_a_x11300_multi_slave_spi_transport_1_1_config.html", null ],
    [ "daisy::Mcp23017Transport::Config", "structdaisy_1_1_mcp23017_transport_1_1_config.html", null ],
    [ "daisy::Mcp23X17< Transport >::Config", "structdaisy_1_1_mcp23_x17_1_1_config.html", null ],
    [ "daisy::MidiHandler< Transport >::Config", "structdaisy_1_1_midi_handler_1_1_config.html", null ],
    [ "daisy::MidiUartTransport::Config", "structdaisy_1_1_midi_uart_transport_1_1_config.html", null ],
    [ "daisy::MidiUsbTransport::Config", "structdaisy_1_1_midi_usb_transport_1_1_config.html", null ],
    [ "daisy::Mpr121< Transport >::Config", "structdaisy_1_1_mpr121_1_1_config.html", null ],
    [ "daisy::Mpr121I2CTransport::Config", "structdaisy_1_1_mpr121_i2_c_transport_1_1_config.html", null ],
    [ "daisy::MultiSlaveSpiHandle::Config", "structdaisy_1_1_multi_slave_spi_handle_1_1_config.html", null ],
    [ "daisy::NeoPixel< Transport >::Config", "structdaisy_1_1_neo_pixel_1_1_config.html", null ],
    [ "daisy::NeoPixelI2CTransport::Config", "structdaisy_1_1_neo_pixel_i2_c_transport_1_1_config.html", null ],
    [ "daisy::NeoTrellis< Transport >::Config", "structdaisy_1_1_neo_trellis_1_1_config.html", null ],
    [ "daisy::NeoTrellisI2CTransport::Config", "structdaisy_1_1_neo_trellis_i2_c_transport_1_1_config.html", null ],
    [ "daisy::OledDisplay< DisplayDriver >::Config", "structdaisy_1_1_oled_display_1_1_config.html", null ],
    [ "daisy::QSPIHandle::Config", "structdaisy_1_1_q_s_p_i_handle_1_1_config.html", null ],
    [ "daisy::SaiHandle::Config", "structdaisy_1_1_sai_handle_1_1_config.html", null ],
    [ "daisy::SdmmcHandler::Config", "structdaisy_1_1_sdmmc_handler_1_1_config.html", null ],
    [ "daisy::ShiftRegister4021< num_daisychained, num_parallel >::Config", "structdaisy_1_1_shift_register4021_1_1_config.html", null ],
    [ "daisy::SpiHandle::Config", "structdaisy_1_1_spi_handle_1_1_config.html", null ],
    [ "daisy::SSD130x4WireSoftSpiTransport::Config", "structdaisy_1_1_s_s_d130x4_wire_soft_spi_transport_1_1_config.html", null ],
    [ "daisy::SSD130x4WireSpiTransport::Config", "structdaisy_1_1_s_s_d130x4_wire_spi_transport_1_1_config.html", null ],
    [ "daisy::SSD130xDriver< width, height, Transport >::Config", "structdaisy_1_1_s_s_d130x_driver_1_1_config.html", null ],
    [ "daisy::SSD130xI2CTransport::Config", "structdaisy_1_1_s_s_d130x_i2_c_transport_1_1_config.html", null ],
    [ "daisy::System::Config", "structdaisy_1_1_system_1_1_config.html", null ],
    [ "daisy::TimerHandle::Config", "structdaisy_1_1_timer_handle_1_1_config.html", null ],
    [ "daisy::Tlv493d< Transport >::Config", "structdaisy_1_1_tlv493d_1_1_config.html", null ],
    [ "daisy::Tlv493dI2CTransport::Config", "structdaisy_1_1_tlv493d_i2_c_transport_1_1_config.html", null ],
    [ "daisy::UartHandler::Config", "structdaisy_1_1_uart_handler_1_1_config.html", null ],
    [ "daisy::USBHostHandle::Config", "structdaisy_1_1_u_s_b_host_handle_1_1_config.html", null ],
    [ "daisy::WavWriter< transfer_size >::Config", "structdaisy_1_1_wav_writer_1_1_config.html", null ],
    [ "daisy::Wm8731::Config", "structdaisy_1_1_wm8731_1_1_config.html", null ],
    [ "daisy::ControlChangeEvent", "structdaisy_1_1_control_change_event.html", null ],
    [ "daisy::CpuLoadMeter", "classdaisy_1_1_cpu_load_meter.html", null ],
    [ "daisy::AbstractMenu::CustomItem", "classdaisy_1_1_abstract_menu_1_1_custom_item.html", null ],
    [ "daisy::DacHandle", "classdaisy_1_1_dac_handle.html", null ],
    [ "daisy::DaisyField", "classdaisy_1_1_daisy_field.html", null ],
    [ "daisy::DaisyLegio", "classdaisy_1_1_daisy_legio.html", null ],
    [ "daisy::DaisyPatch", "classdaisy_1_1_daisy_patch.html", null ],
    [ "daisy::patch_sm::DaisyPatchSM", "classdaisy_1_1patch__sm_1_1_daisy_patch_s_m.html", null ],
    [ "daisy::DaisyPetal", "classdaisy_1_1_daisy_petal.html", null ],
    [ "daisy::DaisyPod", "classdaisy_1_1_daisy_pod.html", null ],
    [ "daisy::DaisySeed", "classdaisy_1_1_daisy_seed.html", null ],
    [ "daisy::DaisyVersio", "classdaisy_1_1_daisy_versio.html", null ],
    [ "daisy::MAX11300Types::DmaBuffer", "structdaisy_1_1_m_a_x11300_types_1_1_dma_buffer.html", null ],
    [ "daisy::DotStar< Transport >", "classdaisy_1_1_dot_star.html", null ],
    [ "daisy::DotStarSpiTransport", "classdaisy_1_1_dot_star_spi_transport.html", null ],
    [ "daisy::Dps310< Transport >", "classdaisy_1_1_dps310.html", null ],
    [ "daisy::Dps310I2CTransport", "classdaisy_1_1_dps310_i2_c_transport.html", null ],
    [ "daisy::Dps310SpiTransport", "classdaisy_1_1_dps310_spi_transport.html", null ],
    [ "dsy_gpio", "structdsy__gpio.html", null ],
    [ "dsy_gpio_pin", "structdsy__gpio__pin.html", null ],
    [ "DSY_SD_CardInfoTypeDef", "struct_d_s_y___s_d___card_info_type_def.html", null ],
    [ "daisy::Encoder", "classdaisy_1_1_encoder.html", null ],
    [ "daisy::FatFSInterface", "classdaisy_1_1_fat_f_s_interface.html", null ],
    [ "daisy::FIFOBase< T >", "classdaisy_1_1_f_i_f_o_base.html", [
      [ "daisy::FIFO< daisy::MidiEvent, 256 >", "classdaisy_1_1_f_i_f_o.html", null ],
      [ "daisy::FIFO< Event, 256 >", "classdaisy_1_1_f_i_f_o.html", null ],
      [ "daisy::FIFO< T, capacity >", "classdaisy_1_1_f_i_f_o.html", null ]
    ] ],
    [ "daisy::FIFOBase< daisy::MidiEvent >", "classdaisy_1_1_f_i_f_o_base.html", null ],
    [ "daisy::FIFOBase< Event >", "classdaisy_1_1_f_i_f_o_base.html", null ],
    [ "daisy::FixedCapStrBase< CharType >", "classdaisy_1_1_fixed_cap_str_base.html", [
      [ "daisy::FixedCapStr< capacity, CharType >", "classdaisy_1_1_fixed_cap_str.html", null ]
    ] ],
    [ "daisy::FixedCapStrBase< char >", "classdaisy_1_1_fixed_cap_str_base.html", null ],
    [ "FontDef", "struct_font_def.html", null ],
    [ "daisy::GateIn", "classdaisy_1_1_gate_in.html", null ],
    [ "daisy::GPIO", "classdaisy_1_1_g_p_i_o.html", null ],
    [ "daisy::I2CHandle", "classdaisy_1_1_i2_c_handle.html", null ],
    [ "daisy::Icm20948< Transport >", "classdaisy_1_1_icm20948.html", null ],
    [ "daisy::Icm20948I2CTransport", "classdaisy_1_1_icm20948_i2_c_transport.html", null ],
    [ "daisy::Icm20948SpiTransport", "classdaisy_1_1_icm20948_spi_transport.html", null ],
    [ "daisy::Icm20948< Transport >::Icm20948Vect", "structdaisy_1_1_icm20948_1_1_icm20948_vect.html", null ],
    [ "daisy::AbstractMenu::ItemConfig", "structdaisy_1_1_abstract_menu_1_1_item_config.html", null ],
    [ "daisy::NeoTrellis< Transport >::keyEvent", "uniondaisy_1_1_neo_trellis_1_1key_event.html", null ],
    [ "daisy::NeoTrellis< Transport >::keyEventRaw", "uniondaisy_1_1_neo_trellis_1_1key_event_raw.html", null ],
    [ "daisy::NeoTrellis< Transport >::keyState", "uniondaisy_1_1_neo_trellis_1_1key_state.html", null ],
    [ "daisy::LcdHD44780", "classdaisy_1_1_lcd_h_d44780.html", null ],
    [ "daisy::Led", "classdaisy_1_1_led.html", null ],
    [ "daisy::LedDriverPca9685< numDrivers, persistentBufferContents >", "classdaisy_1_1_led_driver_pca9685.html", null ],
    [ "daisy::LedDriverPca9685< 2, true >", "classdaisy_1_1_led_driver_pca9685.html", null ],
    [ "daisy::LocalControlEvent", "structdaisy_1_1_local_control_event.html", null ],
    [ "daisy::Logger< dest >", "classdaisy_1_1_logger.html", null ],
    [ "daisy::Logger< LOGGER_NONE >", "classdaisy_1_1_logger_3_01_l_o_g_g_e_r___n_o_n_e_01_4.html", null ],
    [ "daisy::LoggerImpl< dest >", "classdaisy_1_1_logger_impl.html", null ],
    [ "daisy::LoggerImpl< LOGGER_EXTERNAL >", "classdaisy_1_1_logger_impl_3_01_l_o_g_g_e_r___e_x_t_e_r_n_a_l_01_4.html", null ],
    [ "daisy::LoggerImpl< LOGGER_INTERNAL >", "classdaisy_1_1_logger_impl_3_01_l_o_g_g_e_r___i_n_t_e_r_n_a_l_01_4.html", null ],
    [ "daisy::LoggerImpl< LOGGER_SEMIHOST >", "classdaisy_1_1_logger_impl_3_01_l_o_g_g_e_r___s_e_m_i_h_o_s_t_01_4.html", null ],
    [ "daisy::MappedValue", "classdaisy_1_1_mapped_value.html", [
      [ "daisy::MappedFloatValue", "classdaisy_1_1_mapped_float_value.html", null ],
      [ "daisy::MappedIntValue", "classdaisy_1_1_mapped_int_value.html", null ],
      [ "daisy::MappedStringListValue", "classdaisy_1_1_mapped_string_list_value.html", null ]
    ] ],
    [ "daisy::MAX11300Driver< Transport, num_devices >", "classdaisy_1_1_m_a_x11300_driver.html", null ],
    [ "daisy::MAX11300MultiSlaveSpiTransport", "classdaisy_1_1_m_a_x11300_multi_slave_spi_transport.html", null ],
    [ "daisy::Mcp23017Transport", "classdaisy_1_1_mcp23017_transport.html", null ],
    [ "daisy::Mcp23X17< Transport >", "classdaisy_1_1_mcp23_x17.html", null ],
    [ "daisy::MidiEvent", "structdaisy_1_1_midi_event.html", null ],
    [ "daisy::MidiHandler< Transport >", "classdaisy_1_1_midi_handler.html", null ],
    [ "daisy::MidiHandler< MidiUartTransport >", "classdaisy_1_1_midi_handler.html", null ],
    [ "daisy::MidiParser", "classdaisy_1_1_midi_parser.html", null ],
    [ "daisy::MidiUartTransport", "classdaisy_1_1_midi_uart_transport.html", null ],
    [ "daisy::MidiUsbTransport", "classdaisy_1_1_midi_usb_transport.html", null ],
    [ "daisy::MonoModeOnEvent", "structdaisy_1_1_mono_mode_on_event.html", null ],
    [ "daisy::Mpr121< Transport >", "classdaisy_1_1_mpr121.html", null ],
    [ "daisy::Mpr121I2CTransport", "classdaisy_1_1_mpr121_i2_c_transport.html", null ],
    [ "daisy::MTCQuarterFrameEvent", "structdaisy_1_1_m_t_c_quarter_frame_event.html", null ],
    [ "daisy::MultiSlaveSpiHandle", "classdaisy_1_1_multi_slave_spi_handle.html", null ],
    [ "daisy::NeoPixel< Transport >", "classdaisy_1_1_neo_pixel.html", null ],
    [ "daisy::NeoPixel< NeoPixelI2CTransport >", "classdaisy_1_1_neo_pixel.html", null ],
    [ "daisy::NeoPixelI2CTransport", "classdaisy_1_1_neo_pixel_i2_c_transport.html", null ],
    [ "daisy::NeoTrellis< Transport >", "classdaisy_1_1_neo_trellis.html", null ],
    [ "daisy::NeoTrellisI2CTransport", "classdaisy_1_1_neo_trellis_i2_c_transport.html", null ],
    [ "daisy::NoteOffEvent", "structdaisy_1_1_note_off_event.html", null ],
    [ "daisy::NoteOnEvent", "structdaisy_1_1_note_on_event.html", null ],
    [ "daisy::OmniModeOffEvent", "structdaisy_1_1_omni_mode_off_event.html", null ],
    [ "daisy::OmniModeOnEvent", "structdaisy_1_1_omni_mode_on_event.html", null ],
    [ "daisy::OneBitGraphicsDisplay", "classdaisy_1_1_one_bit_graphics_display.html", [
      [ "daisy::OneBitGraphicsDisplayImpl< OledDisplay< DisplayDriver > >", "classdaisy_1_1_one_bit_graphics_display_impl.html", [
        [ "daisy::OledDisplay< DisplayDriver >", "classdaisy_1_1_oled_display.html", null ]
      ] ],
      [ "daisy::OneBitGraphicsDisplayImpl< OledDisplay< daisy::SSD130xDriver > >", "classdaisy_1_1_one_bit_graphics_display_impl.html", null ],
      [ "daisy::OneBitGraphicsDisplayImpl< ChildType >", "classdaisy_1_1_one_bit_graphics_display_impl.html", [
        [ "daisy::OledDisplay< daisy::SSD130xDriver >", "classdaisy_1_1_oled_display.html", null ]
      ] ]
    ] ],
    [ "daisy::Parameter", "classdaisy_1_1_parameter.html", null ],
    [ "daisy::Pcm3060", "classdaisy_1_1_pcm3060.html", null ],
    [ "daisy::PersistentStorage< SettingStruct >", "classdaisy_1_1_persistent_storage.html", null ],
    [ "daisy::Pin", "structdaisy_1_1_pin.html", null ],
    [ "daisy::MAX11300MultiSlaveSpiTransport::Config< numDevices >::PinConfig", "structdaisy_1_1_m_a_x11300_multi_slave_spi_transport_1_1_config_1_1_pin_config.html", null ],
    [ "daisy::PitchBendEvent", "structdaisy_1_1_pitch_bend_event.html", null ],
    [ "daisy::PolyModeOnEvent", "structdaisy_1_1_poly_mode_on_event.html", null ],
    [ "daisy::PolyphonicKeyPressureEvent", "structdaisy_1_1_polyphonic_key_pressure_event.html", null ],
    [ "daisy::PotMonitor< BackendType, numPots >", "classdaisy_1_1_pot_monitor.html", null ],
    [ "daisy::ProgramChangeEvent", "structdaisy_1_1_program_change_event.html", null ],
    [ "daisy::QSPIHandle", "classdaisy_1_1_q_s_p_i_handle.html", null ],
    [ "daisy::Random", "classdaisy_1_1_random.html", null ],
    [ "daisy::Rectangle", "classdaisy_1_1_rectangle.html", null ],
    [ "daisy::Tlv493d< Transport >::RegMask_t", "structdaisy_1_1_tlv493d_1_1_reg_mask__t.html", null ],
    [ "daisy::ResetAllControllersEvent", "structdaisy_1_1_reset_all_controllers_event.html", null ],
    [ "daisy::RgbLed", "classdaisy_1_1_rgb_led.html", null ],
    [ "daisy::RingBuffer< T, size >", "classdaisy_1_1_ring_buffer.html", null ],
    [ "daisy::RingBuffer< T, 0 >", "classdaisy_1_1_ring_buffer_3_01_t_00_010_01_4.html", null ],
    [ "daisy::SaiHandle", "classdaisy_1_1_sai_handle.html", null ],
    [ "daisy::ScopedIrqBlocker", "classdaisy_1_1_scoped_irq_blocker.html", null ],
    [ "daisy::SdmmcHandler", "classdaisy_1_1_sdmmc_handler.html", null ],
    [ "SdramHandle", "class_sdram_handle.html", null ],
    [ "daisy::ShiftRegister4021< num_daisychained, num_parallel >", "classdaisy_1_1_shift_register4021.html", null ],
    [ "daisy::ShiftRegister4021< 2 >", "classdaisy_1_1_shift_register4021.html", null ],
    [ "ShiftRegister595", "class_shift_register595.html", null ],
    [ "daisy::SongPositionPointerEvent", "structdaisy_1_1_song_position_pointer_event.html", null ],
    [ "daisy::SongSelectEvent", "structdaisy_1_1_song_select_event.html", null ],
    [ "daisy::UI::SpecialControlIds", "structdaisy_1_1_u_i_1_1_special_control_ids.html", null ],
    [ "daisy::SpiHandle", "classdaisy_1_1_spi_handle.html", null ],
    [ "daisy::SSD130x4WireSoftSpiTransport", "classdaisy_1_1_s_s_d130x4_wire_soft_spi_transport.html", null ],
    [ "daisy::SSD130x4WireSpiTransport", "classdaisy_1_1_s_s_d130x4_wire_spi_transport.html", null ],
    [ "daisy::SSD130xDriver< width, height, Transport >", "classdaisy_1_1_s_s_d130x_driver.html", null ],
    [ "daisy::SSD130xI2CTransport", "classdaisy_1_1_s_s_d130x_i2_c_transport.html", null ],
    [ "daisy::StackBase< T >", "classdaisy_1_1_stack_base.html", [
      [ "daisy::Stack< daisy::UiPage *, kMaxNumPages >", "classdaisy_1_1_stack.html", null ],
      [ "daisy::Stack< daisy::UiCanvasDescriptor, kMaxNumCanvases >", "classdaisy_1_1_stack.html", null ],
      [ "daisy::Stack< T, capacity >", "classdaisy_1_1_stack.html", null ]
    ] ],
    [ "daisy::StackBase< daisy::UiCanvasDescriptor >", "classdaisy_1_1_stack_base.html", null ],
    [ "daisy::StackBase< daisy::UiPage * >", "classdaisy_1_1_stack_base.html", null ],
    [ "daisy::Switch", "classdaisy_1_1_switch.html", null ],
    [ "daisy::Switch3", "classdaisy_1_1_switch3.html", null ],
    [ "daisy::System", "classdaisy_1_1_system.html", null ],
    [ "daisy::SystemExclusiveEvent", "structdaisy_1_1_system_exclusive_event.html", null ],
    [ "daisy::TimerHandle", "classdaisy_1_1_timer_handle.html", null ],
    [ "daisy::Tlv493d< Transport >", "classdaisy_1_1_tlv493d.html", null ],
    [ "daisy::Tlv493dI2CTransport", "classdaisy_1_1_tlv493d_i2_c_transport.html", null ],
    [ "daisy::UartHandler", "classdaisy_1_1_uart_handler.html", null ],
    [ "daisy::UI", "classdaisy_1_1_u_i.html", null ],
    [ "daisy::UiCanvasDescriptor", "structdaisy_1_1_ui_canvas_descriptor.html", null ],
    [ "daisy::UiEventQueue", "classdaisy_1_1_ui_event_queue.html", null ],
    [ "daisy::UiPage", "classdaisy_1_1_ui_page.html", [
      [ "daisy::AbstractMenu", "classdaisy_1_1_abstract_menu.html", [
        [ "daisy::FullScreenItemMenu", "classdaisy_1_1_full_screen_item_menu.html", null ]
      ] ]
    ] ],
    [ "UsbHandle", "class_usb_handle.html", null ],
    [ "daisy::USBHostHandle", "classdaisy_1_1_u_s_b_host_handle.html", null ],
    [ "daisy::VoctCalibration", "classdaisy_1_1_voct_calibration.html", null ],
    [ "daisy::WAV_FormatTypeDef", "structdaisy_1_1_w_a_v___format_type_def.html", null ],
    [ "daisy::WaveTableLoader", "classdaisy_1_1_wave_table_loader.html", null ],
    [ "daisy::WavFileInfo", "structdaisy_1_1_wav_file_info.html", null ],
    [ "daisy::WavPlayer", "classdaisy_1_1_wav_player.html", null ],
    [ "daisy::WavWriter< transfer_size >", "classdaisy_1_1_wav_writer.html", null ],
    [ "daisy::Wm8731", "classdaisy_1_1_wm8731.html", null ]
];