# Project Name
TARGET = QSPI_ReadAndWrite

# Sources
CPP_SOURCES = main.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
