# Project Name
TARGET = WavCopy

USE_FATFS = 1

# Sources
CPP_SOURCES = CopyingWavs.cpp \
wav_copy_class.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
