# Project Name
TARGET = CopyingWavs

# This is necessary if we want to use FatFS in our code
USE_FATFS = 1

# Sources
CPP_SOURCES = CopyingWavs.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
