# Project Name
TARGET = WavPlayer

# Sources
CPP_SOURCES = main.cpp

DEBUG=0
OPT=-O3

USE_FATFS=1

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
