# Project Name
TARGET = WavPlayer

# Sources
CPP_SOURCES = main.cpp

DEBUG=1
OPT=-O0

USE_FATFS=1

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
