# Project Name
TARGET = ex_SeedSDMMC

# Sources
CPP_SOURCES = SeedSDMMC.cpp

# Library Locations
LIBDAISY_DIR = ../../../../libdaisy
DAISYSP_DIR = ../../../../daisysp

# Core location, and generic makefile.
SYSTEM_FILES_DIR = ../../../../core
include $(SYSTEM_FILES_DIR)/Makefile

