# Project Name
TARGET = Blocking_Transmit

# Sources
CPP_SOURCES = Blocking_Transmit.cpp

# Library Locations
LIBDAISY_DIR = ../../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
