# Project Name
TARGET = ex_line

# Sources
CPP_SOURCES = ex_line.cpp

# Library Locations
LIBDAISY_DIR = ../../../libdaisy
DAISYSP_DIR = ../../

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = ../../../core
include $(SYSTEM_FILES_DIR)/Makefile

