# Project Name
TARGET = Dma_Receive

# Sources
CPP_SOURCES = Dma_Receive.cpp

# Library Locations
LIBDAISY_DIR = ../../..

OPT=-O0

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
