# Project Name
TARGET = Dma_Transmit_Blocking_Receive

# Sources
CPP_SOURCES = Dma_Transmit_Blocking_Receive.cpp

# Library Locations
LIBDAISY_DIR = ../../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
