# Project Name
TARGET = MIDI_UART_Input

# Sources
CPP_SOURCES = MIDI_UART_Input.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
