# Project Name
TARGET = GPIO_Output

# Sources
CPP_SOURCES = GPIO_Output.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
