# Project Name
TARGET = ex_patch_pluck_echo

# Sources
CPP_SOURCES = PluckEcho.cpp

# Library Locations
LIBDAISY_DIR = ../../../../libdaisy
DAISYSP_DIR = ../../../../daisysp

# Core location, and generic makefile.
SYSTEM_FILES_DIR = ../../../../core
include $(SYSTEM_FILES_DIR)/makefile

