# Project Name
TARGET = SDMMC_WavPlayer

# Sources
CPP_SOURCES = SDMMC_WavPlayer.cpp

# Use FatFS Middleware for SD card access
USE_FATFS = 1

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
