# Project Name
TARGET = WavWriter-Realtime

# Sources
CPP_SOURCES = main.cpp

USE_FATFS=1

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
