# Project Name
TARGET = dma-pwm

# Sources
CPP_SOURCES = dma-pwm.cpp

DEBUG=1
OPT=-O0

C_DEFS += -DDEBUG_DEFAULT_INTERRUPT_HANDLERS

# Library Locations
LIBDAISY_DIR = ../../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
