# Project Name
TARGET = DAC_Polling_Output

# Sources
CPP_SOURCES = DAC_Polling_Output.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
