# Project Name
TARGET = TIM_SingleCallback

# Sources
CPP_SOURCES = TIM_SingleCallback.cpp

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
