# Project Name
TARGET = SDMMC_HelloWorld

# Sources
CPP_SOURCES = SDMMC_HelloWorld.cpp

# USE_FATFS is required when linking the FatFS middleware to your project
USE_FATFS = 1

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
