# Project Name
TARGET = SpiBlockingTransmit

# Sources
CPP_SOURCES = SpiBlockingTransmit.cpp

# Library Locations
LIBDAISY_DIR = ../../../

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
