# Project Name
TARGET = OledSoftSPI

# Sources
CPP_SOURCES = OledSoftSPI.cpp

# Library Locations
LIBDAISY_DIR = ../../

#APP_TYPE = BOOT_SRAM

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
