# Project Name
TARGET = basic-pwm

# Sources
CPP_SOURCES = basic-pwm.cpp

DEBUG=1
OPT=-O0

# Library Locations
LIBDAISY_DIR = ../../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
