name: Build

on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/**'
    - 'ci/**'
    - 'cmake/**'
    - 'core/**'
    - 'Drivers/**'
    - 'src/**'
    - 'tests/**'
    - 'CMakeLists.txt'
    - 'Makefile'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/**'
    - 'ci/**'
    - 'cmake/**'
    - 'core/**'
    - 'Drivers/**'
    - 'src/**'
    - 'tests/**'
    - 'CMakeLists.txt'
    - 'Makefile'

jobs:
  build-makefile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '9-2019-q4'
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build Library
      run: make -j
    - name: Build Examples
      run: ./ci/build_examples.py -f core doc src tests Drivers

  build-cmake-gcc:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [latest, '13.3.Rel1', '12.3.Rel1', '11.3.Rel1', '10.3-2021.10', '9-2020-q2']

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: ${{ matrix.version }}

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release

    - name: Build All
      run: cmake --build build --target examples --verbose

  build-cmake-llvm:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          version: [latest, '19.1.1']

      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM Embedded Toolchain for Arm
        uses: stellar-aria/llvm-embedded-toolchain-for-arm-action@latest
        with:
          release: ${{ matrix.version }}

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release

      - name: Build All
        run: cmake --build build --target BootloaderBlink --verbose # TODO: make this build all examples
